services:
  frontend:
    container_name: vistoria-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped